#!/usr/bin/env python3
"""
quantize_to_int8.py — Float32 ONNX → Int8 C Header Converter
for MiniOS-ESP8266

Reads a float32 ONNX model, extracts weight initializers,
quantizes them to int8 using per-tensor symmetric min-max scaling,
and writes a C header file that can be included directly into the
firmware without any filesystem access.

Usage:
    python3 quantize_to_int8.py <model.onnx> <output_header.h> [--scale 0.01]

Example:
    python3 quantize_to_int8.py tiny_mlp.onnx \\
        ../include/models/tiny_mlp_model.h

Dependencies:
    pip install onnx numpy

The generated header is compatible with onnx_loader_tiny.c.
"""

import sys
import os
import struct
import argparse
import numpy as np

try:
    import onnx
    from onnx import numpy_helper
except ImportError:
    print("Error: 'onnx' package not found. Install with: pip install onnx")
    sys.exit(1)


# ---------------------------------------------------------------------------
#  Quantization helpers
# ---------------------------------------------------------------------------

def quantize_symmetric(weights: np.ndarray, bits: int = 8) -> tuple:
    """
    Quantize weights using symmetric min-max scaling.

    Returns:
        (quantized_int8, scale, zero_point=0)
    """
    abs_max = np.max(np.abs(weights))
    if abs_max == 0.0:
        return np.zeros_like(weights, dtype=np.int8), 1.0, 0

    max_val = (2 ** (bits - 1)) - 1   # 127 for int8
    scale   = abs_max / max_val

    quantized = np.round(weights / scale).astype(np.int32)
    quantized = np.clip(quantized, -128, 127).astype(np.int8)

    return quantized, scale, 0


def format_c_array_int8(name: str, data: np.ndarray, shape: tuple,
                         scale: float, comment: str = "") -> str:
    """Format a numpy int8 array as a C array declaration."""
    flat   = data.flatten()
    n      = len(flat)

    lines  = []
    if comment:
        lines.append(f"/* {comment} — shape={shape}, scale={scale:.6f} */")

    # Multi-dimensional array declaration
    dims = "".join(f"[{d}]" for d in shape)
    lines.append(f"static const int8_t {name}{dims} = {{")

    # Print values in rows of 16
    row_size = shape[-1] if len(shape) > 1 else 16
    idx      = 0
    row_num  = 0
    while idx < n:
        row  = flat[idx:idx + row_size]
        vals = ", ".join(f"{int(v):4d}" for v in row)
        lines.append(f"    {{ {vals} }},  /* row {row_num} */")
        idx     += row_size
        row_num += 1

    lines.append("};")
    return "\n".join(lines)


def format_c_array_1d(name: str, data: np.ndarray, comment: str = "") -> str:
    """Format a 1D numpy int8 array as a C array declaration."""
    flat = data.flatten()
    vals = ", ".join(f"{int(v):4d}" for v in flat)
    comment_str = f"/* {comment} */" if comment else ""
    return f"static const int8_t {name}[{len(flat)}] = {{ {vals} }};  {comment_str}"


# ---------------------------------------------------------------------------
#  ONNX model parsing
# ---------------------------------------------------------------------------

def extract_initializers(model_path: str) -> dict:
    """Load ONNX model and return initializer tensors as numpy arrays."""
    model = onnx.load(model_path)
    graph = model.graph

    initializers = {}
    for init in graph.initializer:
        arr = numpy_helper.to_array(init).astype(np.float32)
        initializers[init.name] = arr

    # Collect graph info
    info = {
        "model_name": os.path.splitext(os.path.basename(model_path))[0],
        "ir_version": model.ir_version,
        "nodes": [{"op": n.op_type, "name": n.name,
                   "inputs": list(n.input), "outputs": list(n.output)}
                  for n in graph.node],
        "inputs":  [i.name for i in graph.input],
        "outputs": [o.name for o in graph.output],
        "initializers": initializers
    }
    return info


# ---------------------------------------------------------------------------
#  Header generation
# ---------------------------------------------------------------------------

def generate_header(model_info: dict, output_path: str) -> None:
    guard = os.path.basename(output_path).upper().replace(".", "_").replace("-", "_")
    model_name = model_info["model_name"].upper()
    c_name     = model_info["model_name"].lower().replace("-", "_")

    lines = []
    lines.append(f"/**")
    lines.append(f" * @file {os.path.basename(output_path)}")
    lines.append(f" * @brief Auto-generated int8-quantized model: {model_info['model_name']}")
    lines.append(f" * Generated by: quantize_to_int8.py")
    lines.append(f" * Source: {os.path.basename(output_path).replace('.h','.onnx')}")
    lines.append(f" *")
    lines.append(f" * DO NOT EDIT — regenerate with quantize_to_int8.py")
    lines.append(f" */")
    lines.append(f"")
    lines.append(f"#ifndef MINIOS_{guard}")
    lines.append(f"#define MINIOS_{guard}")
    lines.append(f"")
    lines.append(f'#include "types.h"')
    lines.append(f"")

    # Quantize each initializer
    quantized_tensors = {}
    for tname, tdata in model_info["initializers"].items():
        q_data, scale, zp = quantize_symmetric(tdata)
        quantized_tensors[tname] = (q_data, scale, zp, tdata.shape)
        c_var_name = c_name + "_" + tname.replace("/", "_").replace(".", "_").replace(":", "_")

        if len(tdata.shape) == 1:
            lines.append(format_c_array_1d(c_var_name, q_data,
                                            f"bias scale={scale:.6f}"))
        else:
            lines.append(format_c_array_int8(c_var_name, q_data,
                                              tdata.shape, scale))
        lines.append("")

    # Write quantization metadata
    lines.append(f"/* ---- Quantization metadata ---- */")
    lines.append(f"typedef struct {{")
    lines.append(f"    const char *name;")
    lines.append(f"    float       scale;")
    lines.append(f"    int8_t      zero_point;")
    lines.append(f"}} {c_name}_quant_t;")
    lines.append(f"")

    for tname, (q_data, scale, zp, shape) in quantized_tensors.items():
        c_var_name = c_name + "_" + tname.replace("/","_").replace(".","_").replace(":","_")
        safe_name  = tname.replace("/","_").replace(".","_").replace(":","_")
        lines.append(f"static const {c_name}_quant_t {c_name}_quant_{safe_name} = {{")
        lines.append(f'    .name        = "{tname}",')
        lines.append(f"    .scale       = {scale:.8f}f,")
        lines.append(f"    .zero_point  = {zp},")
        lines.append(f"}};")
        lines.append("")

    lines.append(f"#endif /* MINIOS_{guard} */")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated: {output_path}")
    print(f"  Tensors quantized: {len(quantized_tensors)}")
    for tname, (q_data, scale, zp, shape) in quantized_tensors.items():
        orig_bytes = np.prod(shape) * 4
        q_bytes    = np.prod(shape) * 1
        print(f"  [{tname}] shape={shape} scale={scale:.4f}  "
              f"{orig_bytes}B float32 → {q_bytes}B int8  "
              f"({100*(orig_bytes-q_bytes)/orig_bytes:.0f}% smaller)")


# ---------------------------------------------------------------------------
#  CLI entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Quantize ONNX float32 model to int8 C header for ESP8266"
    )
    parser.add_argument("model", help="Input .onnx file path")
    parser.add_argument("output", help="Output .h file path")
    parser.add_argument("--bits", type=int, default=8,
                        help="Quantization bits (default: 8)")
    args = parser.parse_args()

    if not os.path.exists(args.model):
        print(f"Error: model file not found: {args.model}")
        sys.exit(1)

    print(f"Loading: {args.model}")
    model_info = extract_initializers(args.model)
    print(f"  IR version: {model_info['ir_version']}")
    print(f"  Nodes:      {len(model_info['nodes'])}")
    print(f"  Tensors:    {len(model_info['initializers'])}")

    generate_header(model_info, args.output)


if __name__ == "__main__":
    main()
