#!/usr/bin/env python3
"""
embed_storage.py — Generate C arrays from files in src/storage/

Scans src/storage/ recursively and generates:
  - build/gen/initfs_data.h  (declarations)
  - build/gen/initfs_data.c  (byte arrays + entry table)

These are compiled into the kernel so that INITFS_Populate() can
write them into the ULFS /storage mount at boot time.

Usage:
    python3 scripts/embed_storage.py <storage_dir> <output_dir>
    Example: python3 scripts/embed_storage.py src/storage build/gen
"""

import os
import sys
import re


def sanitize_name(path):
    """Convert a file path to a valid C identifier."""
    name = re.sub(r'[^a-zA-Z0-9]', '_', path)
    # Ensure it doesn't start with a digit
    if name and name[0].isdigit():
        name = '_' + name
    return name


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <storage_dir> <output_dir>", file=sys.stderr)
        sys.exit(1)

    storage_dir = sys.argv[1]
    output_dir = sys.argv[2]

    os.makedirs(output_dir, exist_ok=True)

    # Collect all files recursively
    entries = []
    if os.path.isdir(storage_dir):
        for root, _dirs, files in os.walk(storage_dir):
            for fname in sorted(files):
                full_path = os.path.join(root, fname)
                # Relative path from storage_dir (e.g., "models/foo.onnx")
                rel_path = os.path.relpath(full_path, storage_dir)
                entries.append((rel_path, full_path))

    entries.sort(key=lambda e: e[0])

    # Generate .c file
    c_path = os.path.join(output_dir, 'initfs_data.c')
    h_path = os.path.join(output_dir, 'initfs_data.h')

    with open(c_path, 'w') as cf, open(h_path, 'w') as hf:
        # --- Header file ---
        hf.write("/* Auto-generated by embed_storage.py — DO NOT EDIT */\n")
        hf.write("#ifndef INITFS_DATA_H\n")
        hf.write("#define INITFS_DATA_H\n\n")
        hf.write("#include \"types.h\"\n\n")
        hf.write("typedef struct {\n")
        hf.write("    const char          *path;   /* relative path under /storage */\n")
        hf.write("    const unsigned char *data;   /* file content bytes           */\n")
        hf.write("    uint32_t             size;   /* file size in bytes           */\n")
        hf.write("} initfs_entry_t;\n\n")
        hf.write(f"#define INITFS_NUM_ENTRIES {len(entries)}U\n\n")
        hf.write("extern const initfs_entry_t initfs_entries[];\n\n")
        hf.write("#endif /* INITFS_DATA_H */\n")

        # --- C file ---
        cf.write("/* Auto-generated by embed_storage.py — DO NOT EDIT */\n")
        cf.write("#include \"initfs_data.h\"\n\n")

        # Emit byte arrays for each file
        for rel_path, full_path in entries:
            var_name = "initfs_blob_" + sanitize_name(rel_path)
            with open(full_path, 'rb') as f:
                data = f.read()

            cf.write(f"/* {rel_path} ({len(data)} bytes) */\n")
            cf.write(f"static const unsigned char {var_name}[] = {{\n")
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
                cf.write(f"    {hex_vals},\n")
            cf.write("};\n\n")

        # Emit entry table
        cf.write("const initfs_entry_t initfs_entries[] = {\n")
        for rel_path, _full_path in entries:
            var_name = "initfs_blob_" + sanitize_name(rel_path)
            # Use forward slashes for ULFS paths
            ulfs_path = rel_path.replace(os.sep, '/')
            with open(_full_path, 'rb') as f:
                size = len(f.read())
            cf.write(f'    {{ "{ulfs_path}", {var_name}, {size}U }},\n')
        cf.write("};\n")

    print(f"[embed_storage] Generated {len(entries)} entries:")
    for rel_path, full_path in entries:
        size = os.path.getsize(full_path)
        print(f"  {rel_path} ({size} bytes)")
    print(f"  -> {c_path}")
    print(f"  -> {h_path}")


if __name__ == '__main__':
    main()
