/* Auto-generated by generate_test_models.py */
/* Model: matmul_model.onnx */

#ifndef MATMUL_MODEL_MODEL_H
#define MATMUL_MODEL_MODEL_H

extern const unsigned char MATMUL_MODEL_ONNX[];
extern const unsigned int MATMUL_MODEL_ONNX_LEN;

#endif /* MATMUL_MODEL_MODEL_H */
