/* Auto-generated by generate_test_models.py */
/* Model: simple_mul.onnx */

#ifndef SIMPLE_MUL_MODEL_H
#define SIMPLE_MUL_MODEL_H

extern const unsigned char SIMPLE_MUL_ONNX[];
extern const unsigned int SIMPLE_MUL_ONNX_LEN;

#endif /* SIMPLE_MUL_MODEL_H */
