/* Auto-generated by generate_test_models.py */
/* Model: simple_relu.onnx */

#ifndef SIMPLE_RELU_MODEL_H
#define SIMPLE_RELU_MODEL_H

extern const unsigned char SIMPLE_RELU_ONNX[];
extern const unsigned int SIMPLE_RELU_ONNX_LEN;

#endif /* SIMPLE_RELU_MODEL_H */
