/* Auto-generated by generate_test_models.py */
/* Model: simple_add.onnx */

#ifndef SIMPLE_ADD_MODEL_H
#define SIMPLE_ADD_MODEL_H

extern const unsigned char SIMPLE_ADD_ONNX[];
extern const unsigned int SIMPLE_ADD_ONNX_LEN;

#endif /* SIMPLE_ADD_MODEL_H */
