/* Auto-generated by generate_test_models.py */
/* Model: two_op_model.onnx */

#ifndef TWO_OP_MODEL_MODEL_H
#define TWO_OP_MODEL_MODEL_H

extern const unsigned char TWO_OP_MODEL_ONNX[];
extern const unsigned int TWO_OP_MODEL_ONNX_LEN;

#endif /* TWO_OP_MODEL_MODEL_H */
